#!/bin/python3

import os
import sys

def countingSort(arr):
    # Create frequency array of size 100
    freq = [0] * 100

    # Count occurrences
    for num in arr:
        freq[num] += 1

    return freq


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
