#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'hackerrankInString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def hackerrankInString(s):
    target = "hackerrank"
    j = 0
    
    for ch in s:
        if j < len(target) and ch == target[j]:
            j += 1
    
    if j == len(target):
        return "YES"
    else:
        return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input().strip()

        result = hackerrankInString(s)

        fptr.write(result + '\n')

    fptr.close()
